before_script:
  - docker info

stages:
  - build
  - deploy
  - clean_up

build:
  stage: build
  script:
    - docker build -t ${CI_PROJECT_NAME} .
  tags:
    - docker-build

deploy:
  stage: deploy
  script:
    - docker tag ${CI_PROJECT_NAME} $( echo $DOCKER_CLOUD_REPO )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO
  only:
    - master
  when: on_success
  tags:
    - docker-build

clean_up:
  stage: clean_up
  script:
    - docker rm $(docker ps -a -q) || true
    - docker rmi $(docker images | awk '/^<none>/ { print $3 }') || true
  tags:
    - docker-build
