before_script:
  - docker info

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t ${CI_PROJECT_NAME} .
  tags:
    - docker-build

deploy:
  stage: deploy
  script:
    - docker tag ${CI_PROJECT_NAME} $( echo $DOCKER_CLOUD_REPO )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO
  only:
    - master
  when: on_success
  tags:
    - docker-build
